

BIT_SIZE = 1
BYTE_SIZE = BIT_SIZE * 8
WORD_SIZE = BYTE_SIZE * 2

# Chars
CHAR_SIZE = BYTE_SIZE
UNSIGNED_CHAR_SIZE = CHAR_SIZE
SIGNED_CHAR_SIZE = CHAR_SIZE

# Short integer
SHORT_SIZE = WORD_SIZE
UNSIGNED_SHORT_SIZE = SHORT_SIZE
SIGNED_SHORT_SIZE = SHORT_SIZE

# Integer
INTEGER_SIZE = SHORT_SIZE * 2
UNSIGNED_INTEGER_SIZE = INTEGER_SIZE
SIGNED_INTEGER_SIZE = INTEGER_SIZE

